baseURL: "/"
theme: PaperMod
title: Kazu Blogs
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
  disableXML: true

taxonomies:
      category: categories
      tag: tags
      series: series

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Source
      url: https://github.com/kazu0429/kazu-blogs

outputs:
    home:
        - HTML
        - RSS
        - JSON
        
params:
    env: production
    disableThemeToggle: false
    # ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowAllPagesInArchive: true
    ShowPageNums: true
    # ShowToc: true
    comments: true
    images: ["images/opengraph-image.png"]
    description: "Kazu Blogsã§ã¯æ©Ÿæ¢°å­¦ç¿’ãƒ»WebæŠ€è¡“ã€ãã—ã¦æ—¥ã€…ã®æ´»å‹•ã«ã¤ã„ã¦æ›¸ã„ã¦ã„ã¾ã™ã€‚ä¸»ã«æ©Ÿæ¢°å­¦ç¿’ã§ã¯PyTorchã€Webã¯ãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰ã«ã¤ã„ã¦ã®å†…å®¹ã‚’å–ã‚Šä¸Šã’ã¦ã„ãäºˆå®šã§ã™ã€‚"

    profileMode:
      enabled: false
      Title: "Kazu Blogs"
      subtitle: >
          ## Hi there ğŸ‘‹

          ã¯ã˜ã‚ã¾ã—ã¦ã€‚ç¾åœ¨å¤§å­¦3å¹´ç”Ÿã®ã‚¢ã‚­ãƒ¢ãƒˆã‚«ã‚ºã‚­ã§ã™ã€‚

          >æ°—ã¾ã¾ã«æ—¥ã€…ã®ã“ã¨ã«ã¤ã„ã¦æ›¸ã„ã¦ã„ããŸã„ã¨æ€ã„ã¾ã™ã€‚

      buttons:
        - name: Technical Posts
          url: archives
        - name: Projects
          url: projects
        - name: Art Posts
          url: design

    homeInfoParams:
        Title: "Kazu Blogs"
        Content: >
          ## Hi there ğŸ‘‹

          - ã¯ã˜ã‚ã¾ã—ã¦ã€‚å¤§å­¦ç”Ÿã®ã‚¢ã‚­ãƒ¢ãƒˆã‚«ã‚ºã‚­ã§ã™ã€‚
          ç§ã«ã¤ã„ã¦ã¯[About](/about)ã§

          - ã“ã®ãƒ–ãƒ­ã‚°ã§ã¯ã€æ©Ÿæ¢°å­¦ç¿’ã‚„Webå‘¨ã‚Šã®æŠ€è¡“çš„ãªã“ã¨ã€ãã—ã¦è‡ªåˆ†ã®æ—¥ã€…ã®ã“ã¨ã«ã¤ã„ã¦æ°—ã¾ã¾ã«æ›¸ã„ã¦ã„ããŸã„ã¨æ€ã„ã¾ã™ã€‚

          - 

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/kazu0429"
        - name: "instagram"
          url: "https://www.instagram.com/kazu__a041/"
        - name: "X"
          url: "https://twitter.com/Akazu0429"
        - name: "applemusic"
          url: ""
        - name: "zenn"
          url: "https://zenn.dev/kazu0429"

    analytics:
      # SiteVerificationTag: ""

    editPost:
      URL: "https://github.com/kazu0429/kazu-blogs/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link
    
    assets:
      favicon: "/favicon.ico"
      favicon16x16:  "/favicon-16x16.png"
      favicon32x32:  "/favicon-32x32.png"
      apple_touch_icon:  "/apple-touch-icon.png"
    
    markup:
      highlight:
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        noClasses: false
        style: monokai

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true